ALTER TABLE feedback ADD COLUMN record_index INTEGER;
ALTER TABLE feedback ADD COLUMN page INTEGER;
ALTER TABLE feedback ADD COLUMN level INTEGER;
ALTER TABLE feedback ADD COLUMN name_zh TEXT;
ALTER TABLE feedback ADD COLUMN name_en TEXT;
ALTER TABLE feedback ADD COLUMN poisoning_code TEXT;
ALTER TABLE feedback ADD COLUMN accidental_code TEXT;
ALTER TABLE feedback ADD COLUMN self_harm_code TEXT;
ALTER TABLE feedback ADD COLUMN assault_code TEXT;
ALTER TABLE feedback ADD COLUMN undetermined_code TEXT;
ALTER TABLE feedback ADD COLUMN adverse_effect_code TEXT;
ALTER TABLE feedback ADD COLUMN feedback_type TEXT;
ALTER TABLE feedback ADD COLUMN proposed_value TEXT;
ALTER TABLE feedback ADD COLUMN url TEXT;
ALTER TABLE feedback ADD COLUMN user_agent TEXT;
ALTER TABLE feedback ADD COLUMN ip_hash TEXT;
ALTER TABLE feedback ADD COLUMN status TEXT NOT NULL DEFAULT 'pending';

CREATE INDEX IF NOT EXISTS idx_feedback_status ON feedback(status);
CREATE INDEX IF NOT EXISTS idx_feedback_record_index ON feedback(record_index);
